@startuml

class UML_editor {
    - menu : MymenuBar 
    - penel : Mypenel
    - toolbar : Mytoolbar
}

class MymenuBar {
    + MymenuBar()

}

class GroupOnclick {

}

class UngroupOnclick {
    
}

class RenameOnclick {
    
}

GroupOnclick --* MymenuBar
UngroupOnclick --* MymenuBar
RenameOnclick --* MymenuBar

class Mytoolbar {


}

class ToolButton {
    -clickedbtn : ToolButton
    # buttonmode : Mymode
    +ToolButton()
    -setclickbtn() : void
}

Mytoolbar *-- ToolButton

class Mymode {
    + mousePressed :void
    + mouseReleased :void
    + mouseDragged :void

}

class Selection
class Createassociation
class Creategeneralization
class Createcomposition
class Createclass
class Createusecase

Mymode <|-- Selection
Mymode <|-- Createassociation
Mymode <|-- Creategeneralization
Mymode <|-- Createcomposition
Mymode <|-- Createclass
Mymode <|-- Createusecase

ToolButton --> Mymode

class Myobject {
    - position : int[]
    + paint : void
    + name : String
    + checkPos : boolean
    + getArea : point[]
}

class Basicobject
class Classobject
class Usecaseobject

class Lineobject
class Associationline
class Compositionline
class Generalizationline

class selectarea
class group {
    - objlist : List<Myobject>
}

Myobject <|-- Basicobject
Myobject <|-- Lineobject
Myobject <|-- selectarea
Myobject <|-- group

Basicobject <|-- Classobject
Basicobject <|-- Usecaseobject
Lineobject <|-- Associationline
Lineobject <|-- Compositionline
Lineobject <|-- Generalizationline

class Mypenel {
    - myPenel : Mypenel
    - chooseMode : Mymode
    - objList : List<Myobject> 
    - selectArea : Myobject
    + Mypenel()
    + setMode : void
    + addObject : void
    + paint : void
    + rename : void

}

UML_editor --> MymenuBar
UML_editor --> Mytoolbar
UML_editor --> Mypenel

Mypenel --> Myobject
Mymode --> Myobject

@enduml